name: Test

on:
  push:
    branches:
    tags:
  pull_request:

env:
  DB_HOST: 0.0.0.0
  DB_PORT: 27017
  DB_CONNECTION: mongodb
  DB_USERNAME: root
  DB_PASSWORD: root
  DB_DATABASE: application
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ['ubuntu-latest']
        php: ['7.3', '7.4']
        mongodb: ['4.0', '4.2']
    services:
      mongo:
        image: mongo:${{ matrix.mongodb}}
        ports:
          - 27017:27017
        env:
          MONGO_INITDB_ROOT_USERNAME: root
          MONGO_INITDB_ROOT_PASSWORD: root

    steps:
      - uses: actions/checkout@v2

      - name: Setup php
        uses: shivammathur/setup-php@2.3.0
        with:
          php-version: ${{ matrix.php }}
          extension: dom, mbstring, mongodb, mcrypt
          coverage: xdebug
          tools: composer

      - name: Show php version
        run: php${{ matrix.php }} -v && composer -V && php -m

      - name: Install dependencies
        run: composer install
      - name: Run database migrations
        run: |
          php${{ matrix.php }} artisan migrate
      - name: Run tests
        run: ./vendor/bin/phpunit
      - name: Run test console command
        run: |
          php${{ matrix.php }} artisan geo:index
